obj-m += ip.o
default:
	ARCH=arm 
	CROSS_COMPILE=armr5-none-eabi-
	make -C /home/andy88980/Desktop/Zynq/linux-xlnx M=$(PWD) modules
clean:
	make -C /home/andy88980/Desktop/Zynq/linux-xlnx M=$(PWD) clean




